name:自动化测试

on:
  push:
  pull_request:

  jobs:
    test:
     runs-on:ubuntu-latest


     steps:
     -name:获取项目代码
     uses:actions/checkout@v4

     -name:安装Python
     uses:actions/setup-python@v5
    
     with:
      python-version:"3.12"


      -name:安装项目依赖
      run:pip install -r requirements.txt

      -name:运行自动化测试
      env:
        DEEPSEEK_API_KEY:test_key
        run:python -m pytest -v